import { IOrderRepository } from '@/domian/repository/IOrderRepository';
import { IProductsRepository } from '@/domian/repository/IProductsRepository';
import { IOfferRepository } from '@/domian/repository/IOfferRepository';
import { IAdminRepository } from '@/domian/repository/IAdminRepository';
import { Order, OrderStatus, PaymentMethodType } from '@/domian/entities/Order';
import { INotificationService } from '@/application/services/NotificationService';
import { OfferType } from '@/domian/entities/Offer';
import { PriceCalculatorService } from '@/application/services/PriceCalculatorService';
import { v4 as uuidv4 } from 'uuid';

interface OrderItemDTO {
    productId: string;
    offerId?: string;
    quantity: number;
    color?: string;
    size?: string;
    price?: number;
}

interface CreateOrderDTO {
    phoneNumber: string;
    customerName: string;
    areaName: string;
    streetName?: string;
    buildingNumber?: string;
    additionalNotes?: string;
    deliveryAgentName: string;
    paymentMethod: PaymentMethodType;
    items: OrderItemDTO[];
}

export class CreateOrderUseCase {
    constructor(
        private orderRepository: IOrderRepository,
        private productsRepository: IProductsRepository,
        private notificationService: INotificationService,
        private adminRepository: IAdminRepository,
        private offerRepository: IOfferRepository,
        private priceCalculatorService: PriceCalculatorService
    ) { }

    async execute(dto: CreateOrderDTO): Promise<{ order: Order; hasFcmToken: boolean }> {
        const {
            phoneNumber,
            customerName,
            areaName,
            streetName,
            buildingNumber,
            additionalNotes,
            deliveryAgentName,
            paymentMethod,
            items
        } = dto;

        if (!items || items.length === 0) {
            throw new Error('Order must contain at least one item.');
        }

        // Validate and calculate total amount using PriceCalculatorService
        const calculation = await this.priceCalculatorService.calculate(items.map(item => ({
            productId: item.productId,
            offerId: item.offerId,
            quantity: item.quantity,
            color: item.color,
            size: item.size
        })));

        // Check if any items had errors during calculation
        const errorItem = calculation.items.find(item => item.error);
        if (errorItem) {
            throw new Error(errorItem.error);
        }

        const orderItems = calculation.items.map(item => ({
            product_id: item.productId,
            offer_id: item.appliedOfferId,
            quantity: item.quantity,
            price: item.finalPrice,
            color: item.color,
            size: item.size
        }));

        const totalAmount = calculation.totalAmount;


        // Create order
        const orderId = uuidv4();
        const order = await this.orderRepository.create(
            {
                id: orderId,
                phone_number: phoneNumber,
                customer_name: customerName,
                area_name: areaName,
                street_name: streetName,
                building_number: buildingNumber,
                additional_notes: additionalNotes,
                delivery_agent_name: deliveryAgentName,
                payment_method: paymentMethod,
                status: OrderStatus.PENDING,
                total_amount: parseFloat(totalAmount.toFixed(2))
                // orderNumber is auto-generated by the database
            },
            orderItems
        );

        // Fetch the order with product details populated
        const orderWithDetails = await this.orderRepository.findById(order.id);
        if (!orderWithDetails) {
            throw new Error('Failed to retrieve created order');
        }

        // Check if user has FCM token
        const hasFcmToken = await this.notificationService.hasFcmToken(phoneNumber);

        // Notify admin about new order
        console.log(`🚀 Triggering admin notification for new order: ${orderWithDetails.id}`);

        // Fetch all admin emails to send notifications to all of them
        const admins = await this.adminRepository.findAll();
        const adminEmails = admins.map(admin => admin.email);

        console.log(`📱 Sending notifications to ${adminEmails.length} admin(s): ${adminEmails.join(', ')}`);

        // Send notification to all admin emails
        await this.notificationService.notifyAdminNewOrder(orderWithDetails, adminEmails);

        return { order: orderWithDetails, hasFcmToken };
    }
}